server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://civicpulse-postgres:5432/civicpulse_db
    username: ${POSTGRES_USER:civicpulse_user}
    password: ${POSTGRES_PASSWORD:civicpulse_secure_password_dev_2026}
  data:
    redis:
      host: civicpulse-redis
      port: 6379
      password: ${REDIS_PASSWORD:civicpulse_redis_pass_dev_2026}
  kafka:
    bootstrap-servers: civicpulse-kafka:29092
  mail:
    host: ${MAIL_HOST:civicpulse-mailpit}
    port: ${MAIL_PORT:1025}
